name: Build and Publish App

on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Build using xcodebuild command
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Build
      run: |
        npm i
        cd macos
        pod install
        xcodebuild -workspace billboard.xcworkspace -scheme billboard-macOS ARCHS='x86_64' ONLY_ACTIVE_ARCH=NO DSTROOT="release" archive
        cd ..
    - name: Get Version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Billboard.app
        path: ./macos/release/Applications/billboard.app
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./macos/release/Applications/billboard.app
        tag_name: ${{ steps.package-version.outputs.current-version}
        name: Release ${{ steps.package-version.outputs.current-version}
        draft: false
        prerelease: false