name: Build and Publish App

on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Build using xcodebuild command
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Get Release Name
      id: set_release_name
      run: |
        version=`cat package.json \
         | grep version \
         | head -1 \
         | awk -F: '{ print $2 }' \
         | sed 's/[",]//g'`
        echo "🥳 Setting release version to: $version"
        echo "::set-output name=current-version::$version"
    - name: Build
      run: |
        npm i
        cd macos
        pod install
        xcodebuild -workspace billboard.xcworkspace -scheme billboard-macOS ARCHS='x86_64' ONLY_ACTIVE_ARCH=NO DSTROOT="release" archive
        cd ..
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Billboard.app
        path: ./macos/release/Applications/billboard.app
    - uses: actions/download-artifact@v2
      with:
        name: Billboard.app
        path: billboard
    - name: Display structure of downloaded files
      run: |
        ls -l
        ls -l billboard
        zip -r billboard.app billboard
        chmod +x billboard.app
        echo "After move"
        ls -l
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.set_release_name.outputs.current-version}}
        release_name: Release ${{ steps.set_release_name.outputs.current-version}}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./billboard.app
        asset_name: billboard.app
        asset_content_type: application/octet-stream
